[package]
name = "spaceflake"
description = "⛄ A distributed generator to create unique IDs with ease in Go; inspired by Twitter's Snowflake"
version = "1.1.1"
edition = "2021"
license-file = "LICENSE.md"
readme = "README.md"

[dependencies]
rand = "0.8.5"
